version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: rush_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rush_dev
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: rush_redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  weaviate:
    image: semitechnologies/weaviate:1.23.0
    container_name: rush_weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'  # 수동 벡터 입력
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  mongodb_data:
  redis_data:
  weaviate_data: